name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: 1.23.7
        
        - name: Go Fmt
          run: go fmt ./...

        - name: Go Vet
          run: go vet ./...

        - name: Tests
          run: go test -v ./...

        - name: Fuzz Uint64 addition
          run: go test -v -fuzz=OverflowAddUint64 -fuzztime=60s ./cashu

        - name: Fuzz Uint64 subtraction
          run: go test -v -fuzz=FuzzUnderflowSubUint64 -fuzztime=60s ./cashu

    mint-integration-tests:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            backend: [LND, CLN]
        steps:
        - uses: actions/checkout@v4

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: 1.23.7

        - name: Mint Integration Tests
          run: go test -v --tags=integration ./mint -args -backend ${{ matrix.backend }}

    wallet-integration-tests:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4

        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: 1.23.7

        - name: Wallet Integration Tests 
          run: go test -v --tags=integration ./wallet